spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authms
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: secret

app:
  jwttoken:
    message: "Login Successful"